// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1771Ysc4jj-GvSVtjE0r3S3VYypmfB6A',
    appId: '1:1020906582315:web:8561e25679ef920691956e',
    messagingSenderId: '1020906582315',
    projectId: 'eshop-minimal-rj0zf',
    authDomain: 'eshop-minimal-rj0zf.firebaseapp.com',
    storageBucket: 'eshop-minimal-rj0zf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwoTeE49ucN2foKQP1hWtk3hpx87jOmHk',
    appId: '1:1020906582315:android:e0cde25941f61f8f91956e',
    messagingSenderId: '1020906582315',
    projectId: 'eshop-minimal-rj0zf',
    storageBucket: 'eshop-minimal-rj0zf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4kjOWfwVMA51pIHk0ITjVlVIHsq1jiCY',
    appId: '1:1020906582315:ios:7442c349925ad5ab91956e',
    messagingSenderId: '1020906582315',
    projectId: 'eshop-minimal-rj0zf',
    storageBucket: 'eshop-minimal-rj0zf.firebasestorage.app',
    iosBundleId: 'com.example.apsFeedback',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4kjOWfwVMA51pIHk0ITjVlVIHsq1jiCY',
    appId: '1:1020906582315:ios:7442c349925ad5ab91956e',
    messagingSenderId: '1020906582315',
    projectId: 'eshop-minimal-rj0zf',
    storageBucket: 'eshop-minimal-rj0zf.firebasestorage.app',
    iosBundleId: 'com.example.apsFeedback',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1771Ysc4jj-GvSVtjE0r3S3VYypmfB6A',
    appId: '1:1020906582315:web:fb0479abda60b2eb91956e',
    messagingSenderId: '1020906582315',
    projectId: 'eshop-minimal-rj0zf',
    authDomain: 'eshop-minimal-rj0zf.firebaseapp.com',
    storageBucket: 'eshop-minimal-rj0zf.firebasestorage.app',
  );
}
